apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: spring-demo-actuator
        image: spring-demo:0.0.1
        imagePullPolicy: IfNotPresent


